[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[logger]
level = "INFO"
